### PR TITLE
CORE-3420 Fix maven_rollbacksql.md

### LINKED ISSUE #120: rollbackSQL documentation is broken
http://www.liquibase.org/documentation/maven/maven_rollbacksql.html

Actual result:

image

### PR DESCRIPTION
**Pull request by kubukoz**
Hopefully closes #120 

Edit, 26.04.2019: Created a JIRA issue. https://liquibase.jira.com/browse/CORE-3420

### CODE REVIEW

**Comment by kubukoz** [comment]
@nvoxland would you have a moment to look at this? Thanks :)

**Comment by kubukoz** [comment]
@nvoxland ping ;)

**Comment by ianmcderp** [comment]
Successfully tested and validated in Google Chrome (see attachment below).

image

**Comment by r2datical** [comment]
Thank you!!!

**Comment by kubukoz** [comment]
Thank you for meeting! Almost a 1yr anniversary ;)

**Pull request merged**
